name: Docker Compose
on:
  push:
    branches:
      - 'staging'
      - 'master'

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Log in to Docker Hub
        run: echo "${{ secrets.DOCKERHUB_PWD }}" | docker login --username ${{ secrets.DOCKERHUB_USR }} --password-stdin
      
      - name: Pull latest Docker images
        run: docker-compose -f docker-compose.yml pull

      - name: Build Docker images
        run: docker-compose -f docker-compose.yml build
      
      - name: Run Docker Compose
        run: docker-compose -f docker-compose.yml up -d
      
      # Optional: Clean up resources after the workflow completes
      - name: Stop and remove Docker containers
        run: docker-compose -f docker-compose.yml down  