name: build-staging-master
on:
  push:
    branches:
      - 'staging'
      - 'master'

jobs:
  read-build-config:
    name: Read Build Configuration
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: 3.x

      - name: Install PyYAML
        run: pip install pyyaml

      - name: Read Build Config
        id: read-build-yaml
        run: |
          echo "build_config=$(cat build/build.yml)" >> $GITHUB_ENV
          python -c 'import sys, yaml; print(yaml.safe_load(sys.stdin)["applications"])'

  spark-latest-images:
    name: Spark Images (latest)
    needs: read-build-config
    runs-on: ubuntu-latest
    env:
      DOCKERHUB_USR: ${{ secrets.DOCKERHUB_USR }}
      DOCKERHUB_PWD: ${{ secrets.DOCKERHUB_PWD }}
      SCALA_VERSION: ${{ needs.read-build-config.outputs.build_config.scala }}
      SPARK_VERSION: ${{ needs.read-build-config.outputs.build_config.spark }}
      HADOOP_VERSION: ${{ needs.read-build-config.outputs.build_config.hadoop }}
      IS_LATEST: "true"
    steps:
      - name: Checkout Code
        uses: actions/checkout@v2
      - name: Build Spark v3.0.0 (latest)
        uses: ./.github/actions/build-spark
        with:
          DOCKERHUB_USR: ${{ env.DOCKERHUB_USR }}
          DOCKERHUB_PWD: ${{ env.DOCKERHUB_PWD }}
          SCALA_VERSION: ${{ env.SCALA_VERSION }}
          SPARK_VERSION: ${{ env.SPARK_VERSION }}
          HADOOP_VERSION: ${{ env.HADOOP_VERSION }}
          IS_LATEST: ${{ env.IS_LATEST }}

  spark-images:
    name: Spark Images
    needs: read-build-config
    runs-on: ubuntu-latest
    env:
      DOCKERHUB_USR: ${{ secrets.DOCKERHUB_USR }}
      DOCKERHUB_PWD: ${{ secrets.DOCKERHUB_PWD }}
      SCALA_VERSION: ${{ needs.read-build-config.outputs.build_config.scala }}
      SPARK_VERSION: ${{ needs.read-build-config.outputs.build_config.spark }}
      HADOOP_VERSION: ${{ needs.read-build-config.outputs.build_config.hadoop }}
    strategy:
      matrix:
        spark_version: [ "2.4.4", "2.4.0" ]
    steps:
      - name: Checkout Code
        uses: actions/checkout@v2
      - name: Build Spark v2.4.4 + v2.4.0
        uses: ./.github/actions/build-spark
        with:
          DOCKERHUB_USR: ${{ env.DOCKERHUB_USR }}
          DOCKERHUB_PWD: ${{ env.DOCKERHUB_PWD }}
          SCALA_VERSION: ${{ env.SCALA_VERSION }}
          SPARK_VERSION: ${{ matrix.spark_version }}
          HADOOP_VERSION: ${{ env.HADOOP_VERSION }}

  jupyterlab-latest-images:
    name: JupyterLab Images (latest)
    needs: read-build-config
    runs-on: ubuntu-latest
    env:
      DOCKERHUB_USR: ${{ secrets.DOCKERHUB_USR }}
      DOCKERHUB_PWD: ${{ secrets.DOCKERHUB_PWD }}
      SCALA_VERSION: ${{ needs.read-build-config.outputs.build_config.scala }}
      SCALA_KERNEL_VERSION: ${{ needs.read-build-config.outputs.build_config.scala_kernel }}
      SPARK_VERSION: ${{ needs.read-build-config.outputs.build_config.spark }}
      JUPYTERLAB_VERSION: ${{ needs.read-build-config.outputs.build_config.jupyterlab }}
      IS_LATEST: "true"
    steps:
      - name: Checkout Code
        uses: actions/checkout@v2
      - name: Build JupyterLab v3.0.0 and Spark v3.0.0 (latest)
        uses: ./.github/actions/build-jupyterlab
        with:
          DOCKERHUB_USR: ${{ env.DOCKERHUB_USR }}
          DOCKERHUB_PWD: ${{ env.DOCKERHUB_PWD }}
          SCALA_VERSION: ${{ env.SCALA_VERSION }}
          SCALA_KERNEL_VERSION: ${{ env.SCALA_KERNEL_VERSION }}
          SPARK_VERSION: ${{ env.SPARK_VERSION }}
          JUPYTERLAB_VERSION: ${{ env.JUPYTERLAB_VERSION }}
          IS_LATEST: ${{ env.IS_LATEST }}

      - name: Build JupyterLab v2.1.4 and Spark v3.0.0
        uses: ./.github/actions/build-jupyterlab
        with:
          DOCKERHUB_USR: ${{ env.DOCKERHUB_USR }}
          DOCKERHUB_PWD: ${{ env.DOCKERHUB_PWD }}
          SCALA_VERSION: ${{ env.SCALA_VERSION }}
          SCALA_KERNEL_VERSION: ${{ env.SCALA_KERNEL_VERSION }}
          SPARK_VERSION: ${{ env.SPARK_VERSION }}
          JUPYTERLAB_VERSION: ${{ env.JUPYTERLAB_VERSION }}
          IS_LATEST: ${{ env.IS_LATEST }}

  jupyterlab-images:
    name: JupyterLab Images
    needs: read-build-config
    runs-on: ubuntu-latest
    env:
      DOCKERHUB_USR: ${{ secrets.DOCKERHUB_USR }}
      DOCKERHUB_PWD: ${{ secrets.DOCKERHUB_PWD }}
      SCALA_VERSION: ${{ needs.read-build-config.outputs.build_config.scala }}
      SCALA_KERNEL_VERSION: ${{ needs.read-build-config.outputs.build_config.scala_kernel }}
      SPARK_VERSION: ${{ needs.read-build-config.outputs.build_config.spark }}
      JUPYTERLAB_VERSION: ${{ needs.read-build-config.outputs.build_config.jupyterlab }}
    strategy:
      matrix:
        spark_version: [ "2.4.4", "2.4.0" ]
        jupyterlab_version: [ "3.0.0", "2.1.4" ]
    steps:
      - name: Checkout Code
        uses: actions/checkout@v2
      - name: Build JupyterLab v3.0.0 + v2.1.4 and Spark v2.4.4 + v2.4.0
        uses: ./.github/actions/build-jupyterlab
        with:
          DOCKERHUB_USR: ${{ env.DOCKERHUB_USR }}
          DOCKERHUB_PWD: ${{ env.DOCKERHUB_PWD }}
          SCALA_VERSION: ${{ env.SCALA_VERSION }}
          SCALA_KERNEL_VERSION: ${{ env.SCALA_KERNEL_VERSION }}
          SPARK_VERSION: ${{ matrix.spark_version }}
          JUPYTERLAB_VERSION: ${{ matrix.jupyterlab_version }}


